### ISSUE TITLE
Exception on joining developer channel

### ISSUE THREAD

**Issue by logc** [evanyeung/terminal-slack#19]
I could join my team's main channel on Slack, but when trying to join the "devroom" channel, which is intended for developers talking about non-work related stuff, the app crashes with the following stacktrace:

```
➤ node main.js
TypeError: Cannot read property 'ts' of undefined
    at /Users/logc/Applications/terminal-slack/main.js:150:60
    at /Users/logc/Applications/terminal-slack/slackClient.js:65:30
    at Request._callback (/Users/logc/Applications/terminal-slack/slackClient.js:34:25)
    at Request.self.callback (/Users/logc/Applications/terminal-slack/node_modules/request/request.js:368:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/Users/logc/Applications/terminal-slack/node_modules/request/request.js:1219:14)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/Users/logc/Applications/terminal-slack/node_modules/request/request.js:1167:12)
```

The code is cloned from this repository, at commit c21b181.

Thanks for your work on this app!

**Comment by evanyeung** [comment]
Thanks for bringing this up. There was a bug when no messages were in the channel yet. This is fixed in commit 5e526d.
