### ISSUE TITLE
Application Crashes Randomly

### ISSUE THREAD

**Issue by jamrizzi** [evanyeung/terminal-slack#26]
The application randomly crashes when I try and navigate around it.  It gives me the following error.

```
TypeError: undefined is not a function
    at Textbox.<anonymous> (/opt/terminal-slack/userInterface.js:228:36)
    at Textbox.EventEmitter._emit (/opt/terminal-slack/node_modules/blessed/lib/events.js:98:20)
    at Textbox.EventEmitter.emit (/opt/terminal-slack/node_modules/blessed/lib/events.js:117:12)
    at Program.<anonymous> (/opt/terminal-slack/node_modules/blessed/lib/widgets/screen.js:602:15)
    at Program.emit (events.js:110:17)
    at /opt/terminal-slack/node_modules/blessed/lib/program.js:410:15
    at Array.forEach (native)
    at ReadStream.input.on.input._keypressHandler (/opt/terminal-slack/node_modules/blessed/lib/program.js:408:23)
    at ReadStream.emit (events.js:110:17)
    at /opt/terminal-slack/node_modules/blessed/lib/keys.js:318:14
```

**Comment by evanyeung** [comment]
Which version of node are you using? According to http://node.green/#Array-prototype-includes, `Array.prototype.includes` requires a harmony flag in v5.x and is unsupported in v4.x. It should be supported in v6.x (the latest LTS) and up. It looks like this is probably the error you're running in to.

**Comment by jamrizzi** [comment]
I was using node 4.  That was my problem. I upgraded to 6 and it works like a charm.
