### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by laxdog** [evanyeung/terminal-slack#32]
Running on OSX 10.12.2, node v7.4.0

It's happening when I try to use the slack plugin meekan, when I try to set up a meeting the bot's response kills the client. I've attached a screenshot of the response that did it. 

<img width="511" alt="screen shot 2017-01-31 at 4 16 25 pm" src="https://cloud.githubusercontent.com/assets/794502/22473417/c467fac4-e7d0-11e6-8ef7-a6384c448568.png">

```
TypeError: Cannot read property 'name' of undefined
    at handleNewMessage (/Users/mrobinson/source/slack-cli/terminal-slack/main.js:56:5)
    at WebSocket.<anonymous> (/Users/mrobinson/source/slack-cli/terminal-slack/main.js:81:7)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/Users/mrobinson/source/slack-cli/terminal-slack/node_modules/ws/lib/WebSocket.js:797:10)
    at /Users/mrobinson/source/slack-cli/terminal-slack/node_modules/ws/lib/Receiver.js:473:18
    at Receiver.applyExtensions (/Users/mrobinson/source/slack-cli/terminal-slack/node_modules/ws/lib/Receiver.js:360:5)
    at /Users/mrobinson/source/slack-cli/terminal-slack/node_modules/ws/lib/Receiver.js:462:14
    at Receiver.flush (/Users/mrobinson/source/slack-cli/terminal-slack/node_modules/ws/lib/Receiver.js:336:3)
    at Receiver.finish (/Users/mrobinson/source/slack-cli/terminal-slack/node_modules/ws/lib/Receiver.js:478:12)
```

**Comment by evanyeung** [comment]
Hi @laxdog, thanks for the heads up. It looks some bots can post without their user showing up in the user list. I looked into it quickly and it looks like bots should be returned by [users.list](https://api.slack.com/methods/users.list) but I guess not all bots are. Or at least, it breaks responses from bots with special integrations like buttons (which aren't supported in the terminal right now).

I've added a fix in commit 2b9982fae74e05c60c305d0d19e4eaaec695465b that shows "Unknown User" if the user is not found. This should at least allow you to keep using the app for now.

**Comment by laxdog** [comment]
Thanks!

**Comment by hz-stevec** [comment]
Shall we open another issue for the "Unknown User" showing up? It seems that between the CircleCI bot and the Github bot it shows none of the text and none of the users, and that's the majority of the traffic I need to see, so this fix effectively breaks slack for me anyways. :/

Thank you much for looking into it!
