### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by moschan** [evanyeung/terminal-slack#36]
# Expected behavior
Running without error.

# Actual behavior
showing an error when I execute `node main.js`
An error detail is following.

# Others
- node version is `v5.2.0`
- SLACK_TOKEN is already exported.

Error message is following:

```
bash-4.4$ node main.js
[Path to root]/main.js:8
let users;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:54:16)
    at Module._compile (module.js:375:25)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)
    at node.js:977:3
```

**Comment by moschan** [comment]
oh, I found an existing issue. https://github.com/evanyeung/terminal-slack/issues/34
