### ISSUE TITLE
node main.js TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by stango1212** [evanyeung/terminal-slack#37]
node main.js
TypeError: Cannot read property 'find' of undefined

Now and again i get this error, sometimes slack it works, sometimes i am blocked.

**Comment by evanyeung** [comment]
Hi @stango1212, it looks like this might be possible if there is an error getting the users from Slack. But I'm not sure what the root cause would be. Do you have any more information about where the error occurred in the code or what you do to cause it? Thanks

**Comment by eliaslaouiti** [comment]
Hello,

**Comment by eliaslaouiti** [comment]
Hello, 

I've the same error : 
`TypeError: Cannot read property 'find' of undefined
    at handleNewMessage (/Users/laouitielias/Downloads/terminal-slack/main.js:93:25)
    at WebSocket.ws.on (/Users/laouitielias/Downloads/terminal-slack/main.js:132:7)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/Users/laouitielias/Downloads/terminal-slack/node_modules/ws/lib/WebSocket.js:797:10)
    at /Users/laouitielias/Downloads/terminal-slack/node_modules/ws/lib/Receiver.js:473:18
    at Receiver.applyExtensions (/Users/laouitielias/Downloads/terminal-slack/node_modules/ws/lib/Receiver.js:360:5)
    at /Users/laouitielias/Downloads/terminal-slack/node_modules/ws/lib/Receiver.js:462:14
    at Receiver.flush (/Users/laouitielias/Downloads/terminal-slack/node_modules/ws/lib/Receiver.js:336:3)
    at Receiver.finish (/Users/laouitielias/Downloads/terminal-slack/node_modules/ws/lib/Receiver.js:478:12)`

Thanks

**Comment by elbo1216** [comment]
Hi, 

I have the same error.  It works once in a while but more often than not I get this error message:

TypeError: Cannot read property 'find' of undefined
    at handleNewMessage (/web/terminal-slack/main.js:93:25)
    at WebSocket.ws.on (/web/terminal-slack/main.js:132:7)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/web/terminal-slack/node_modules/ws/lib/WebSocket.js:797:10)
    at /web/terminal-slack/node_modules/ws/lib/Receiver.js:473:18
    at Receiver.applyExtensions (/web/terminal-slack/node_modules/ws/lib/Receiver.js:360:5)
    at /web/terminal-slack/node_modules/ws/lib/Receiver.js:462:14
    at Receiver.flush (/web/terminal-slack/node_modules/ws/lib/Receiver.js:336:3)
    at Receiver.finish (/web/terminal-slack/node_modules/ws/lib/Receiver.js:478:12)

**Comment by dayerdl** [comment]
Same problem. I am using node v7.7.4

DavidDayer-MB-Pro:terminal-slack david$ node main.js
TypeError: Cannot read property 'find' of undefined
    at handleNewMessage (/Users/david/terminal-slack/main.js:93:25)
    at WebSocket.ws.on (/Users/david/terminal-slack/main.js:132:7)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:194:7)
    at Receiver.ontext (/Users/david/terminal-slack/node_modules/ws/lib/WebSocket.js:797:10)
    at /Users/david/terminal-slack/node_modules/ws/lib/Receiver.js:473:18
    at Receiver.applyExtensions (/Users/david/terminal-slack/node_modules/ws/lib/Receiver.js:360:5)
    at /Users/david/terminal-slack/node_modules/ws/lib/Receiver.js:462:14
    at Receiver.flush (/Users/david/terminal-slack/node_modules/ws/lib/Receiver.js:336:3)
    at Receiver.finish (/Users/david/terminal-slack/node_modules/ws/lib/Receiver.js:478:12)

**Comment by h6y3** [comment]
I had the same problem as well.  I did have the session working at some point, then tried to find a user using the /.  Perhaps that had something to do with it?

**Comment by BarbareBzhdev** [comment]
I had same error, and i resolve it after re-issue token. I don't know why ...

**Comment by BarbareBzhdev** [comment]
No it's not that, i have same problem again... sorry :'(
