### ISSUE TITLE
Exit gracefully when SLACK_TOKEN is not set

### ISSUE THREAD

**Issue by osxi** [evanyeung/terminal-slack#9]
I read the README but decided I'd try `node main.js` anyway and got this error:

```
TypeError: Cannot read property 'map' of undefined
    at /home/zach/code/terminal-slack/main.js:77:17
    at Request._callback (/home/zach/code/terminal-slack/slackClient.js:34:26)
    at Request.self.callback (/home/zach/code/terminal-slack/node_modules/request/request.js:368:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/zach/code/terminal-slack/node_modules/request/request.js:1219:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/zach/code/terminal-slack/node_modules/request/request.js:1167:12)
    at emitNone (events.js:72:20)
```

It would be better if the user had a friendly message and followed by `process.exit(1)`.

**Comment by evanyeung** [comment]
This was fixed in commit c21b181dfc15c83e41ba7af8f9fc4c1163b3ec35. Thanks for bringing it up!
